# Generated by Django 5.2.1 on 2025-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
