# Generated by Django 5.2.1 on 2025-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0002_orderdetails_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vanilla', models.PositiveIntegerField(default=0)),
                ('chocolate', models.PositiveIntegerField(default=0)),
                ('strawberry', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('vanilla', models.IntegerField(default=0)),
                ('chocolate', models.IntegerField(default=0)),
                ('strawberry', models.IntegerField(default=0)),
            ],
        ),
    ]
