# Generated by Django 5.2.1 on 2025-05-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0003_product_productstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Product Stock', 'verbose_name_plural': 'Product Stocks'},
        ),
    ]
